version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./scripts/db:/docker-entrypoint-initdb.d
    expose:
      - 5432
    
  my-test-app:
    image: my-app
    command: dockerize -wait tcp://db:5432 -timeout 20s bash -c "yarn jest --coverage"
    environment:
      - NODE_ENV=test
      - NODEMAILER_PASSWORD=${NODEMAILER_PASSWORD}
      - NODEMAILER_EMAIL=${NODEMAILER_EMAIL}
      - SECRET_KEY_ACCESS_TOKEN=${SECRET_KEY_ACCESS_TOKEN}
      - SECRET_KEY_PASSWORD_TOKEN=${SECRET_KEY_PASSWORD_TOKEN}
      - FRONTEND_URL=${FRONTEND_URL}
      - TEST_POSTGRES_URI=postgres://postgres:postgres@db/spes
    depends_on:
      - db

    