version: 'latest'
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5433:5433
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./scripts/db:/docker-entrypoint-initdb.d