version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./scripts/db:/docker-entrypoint-initdb.d
    expose:
      - 5432
    


  my-app:
    image: my-app
    build: .
    environment:
      - NODE_ENV=test
      - NODEMAILER_PASSWORD=${NODEMAILER_PASSWORD}
      - NODEMAILER_EMAIL=${NODEMAILER_EMAIL}
      - SECRET_KEY_ACCESS_TOKEN=${SECRET_KEY_ACCESS_TOKEN}
      - PORT=5000
      - DEV_POSTGRES_URI=postgres://postgres:postgres@db:5432/spes
      - TEST_POSTGRES_URI=postgres://postgres:postgres@db:5432/spes
    command: yarn start:dev
    expose:
      - 3000
    depends_on:
      - db

  my-test-app:
    image: my-app
    command: dockerize -wait tcp://db:5432 -wait tcp://my-app:5000  -timeout 20s bash -c "yarn jest --coverage"
    environment:
      - NODE_ENV=test
      - NODEMAILER_PASSWORD=${NODEMAILER_PASSWORD}
      - NODEMAILER_EMAIL=${NODEMAILER_EMAIL}
      - SECRET_KEY_ACCESS_TOKEN=${SECRET_KEY_ACCESS_TOKEN}
      - TEST_POSTGRES_URI=postgres://postgres:postgres@db:5432/spes
    depends_on:
      - db
      - my-app
    