name: Trigger Render Deployment
on:
  push:
    branches: ['main','develop']
jobs:
  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment
        uses: sws2apps/render-deployment@main
        with:
          apiKey: ${{ secrets.RENDER_API_KEY}}
          apiKey: ${{ secrets.RENDER_SERVICE_ID}}
