name: "UNIT TEST"

on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  run-on: ubuntu-latest
  steps:
    - uses: harmon758/postgresql-action@v1
    - name: Setup Database
    - uses: actions/checkout@v3
    - name: Setup Node
    - run: yarn
