name: "UNIT TEST"

on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

env:
  NODE_ENV: test
  TEST_POSTGRES_URI: postgres://user23:user23@localhost:5432/spes
  SECRET_KEY_ACCESS_TOKEN: KDSLLjuhi4243452oinkKMkgbnopok342324536khjnmCTDYCVJBvucdygjvh65343123425621jhcvKGIUGLNKHG

jobs:
  Unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Database
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: "spes"
          postgresql user: "user23"
          postgresql password: "user23"

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: yarn
      - run: yarn start:dev
      - run: yarn test
